version: '3'

services:
  web:
    image: robol/indico-web
    env_file: indico.env
    ports:
      - 9090:9090
    depends_on:
      - postgres
    volumes:
      - './archive:/indico/archive'
      - './custom:/custom'
      - '.:/indico-unipievents'

  postgres:
    image: postgres:14
    env_file: indico.env
    volumes:
      - ./db-init:/docker-entrypoint-initdb.d
      - ./database:/var/lib/postgresql/data

  redis:
    image: redis
